
const arrOfBooks = [
  { 'isbn13': '9781524763169',
    'author': 'Barack Obama',
    'bookTitle': 'A Promised Land',
    'publisherName': 'Crown Publishing Group',
    'publisherLink': '/publisher',
    'publicationDate': '11/17/2020',
    'series': '',
    'bookCategory': 'Autobiography',
    'ageRange': '',
    'pages': 768,
    'salesRank': 1,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.40(w) x 9.40(h) x 1.50(d)'
  },
  { 'isbn13': '9781571311931',
    'author': 'Aimee Nezhukumatathil',
    'bookTitle': 'World of Wonders: In Praise of Fireflies, Whale Sharks, and Other Astonishments (B&N Exclusive Gift Edition)',
    'publisherName': 'Milkweed Editions',
    'publisherLink': '/publisher',
    'publicationDate': '12/02/2020',
    'series': '',
    'bookCategory': 'Nonfiction',
    'ageRange': '',
    'pages': 184,
    'salesRank': 311,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.50(w) x 1.50(h) x 9.50(d)'
  },
  {'isbn13': '9780765326386',
    'author': 'Brandon Sanderson',
    'bookTitle': 'Rhythm of War (Stormlight Archive Series #4)',
    'publisherName': 'Tom Doherty Associates',
    'publisherLink': '/publisher',
    'publicationDate': '11/17/2020',
    'series': 'Stormlight Archive Series , #4',
    'bookCategory': 'Fiction',
    'ageRange': '',
    'pages': 1232,
    'salesRank': 9,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.60(w) x 9.30(h) x 2.30(d)'
  },
  {'isbn13': '9780316187183',
    'author': 'Joe Abercrombie',
    'bookTitle': 'The Trouble with Peace',
    'publisherName': 'Orbit',
    'publisherLink': '/publisher',
    'publicationDate': '09/15/2020',
    'series': 'Age of Madness Series , #2',
    'bookCategory': 'Fantasy',
    'ageRange': '',
    'pages': 512,
    'salesRank': 25546,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.30(w) x 9.20(h) x 1.70(d)'
  },
  {'isbn13': '9780670020553',
    'author': 'Lev Grossman',
    'bookTitle': 'The Magicians (Magicians Series #1)',
    'publisherName': 'Penguin Publishing Group',
    'publisherLink': '/publisher',
    'publicationDate': '08/11/2009',
    'series': 'Magicians Series , #1',
    'bookCategory': 'Graphic novel',
    'ageRange': '',
    'pages': 416,
    'salesRank': 239071,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.40(w) x 9.30(h) x 1.40(d)'
  },

  {'isbn13': '9780765386489',
    'author': 'Michael Johnston',
    'bookTitle': 'Soleri: A Novel',
    'publisherName': 'Tom Doherty Associates',
    'publisherLink': '/publisher',
    'publicationDate': '06/13/2017',
    'series': 'Amber Throne Series , #1',
    'bookCategory': 'Fantasy',
    'ageRange': '',
    'pages': 368,
    'salesRank': 1255288,
    'format': '',
    'editionDescription': '',
    'productDimensions': '9.30(w) x 6.40(h) x 1.30(d)'
  },
  {'isbn13': '9781250088482',
    'author': 'Isabelle Steiger',
    'bookTitle': 'The Empire\'s Ghost: A Novel',
    'publisherName': 'St. Martin\'\'s Publishing Group',
    'publisherLink': '/publisher',
    'publicationDate': '05/16/2017',
    'series': 'Paths of Lantistyne , #1',
    'bookCategory': 'Fiction',
    'ageRange': '',
    'pages': 432,
    'salesRank': 451282,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.10(w) x 8.70(h) x 1.50(d)'
  },
  {'isbn13': '9781524796372',
    'author': 'Martha Hall Kelly',
    'bookTitle': 'Lost Roses',
    'publisherName': 'Random House Publishing Group',
    'publisherLink': '/publisher',
    'publicationDate': '04/09/2019',
    'series': '',
    'bookCategory': 'Romance',
    'ageRange': '',
    'pages': 448,
    'salesRank': 152488,
    'format': '',
    'editionDescription': '',
    'productDimensions': '5.90(w) x 9.30(h) x 1.70(d)'
  },
  {'isbn13': '9780062667632',
    'author': 'Rumaan Alam',
    'bookTitle': 'Leave the World Behind Alam',
    'publisherName': 'HarperCollins Publishers',
    'publisherLink': '/publisher',
    'publicationDate': '10/06/2020',
    'series': '',
    'bookCategory': 'Nonfiction',
    'ageRange': '',
    'pages': 256,
    'salesRank': 399,
    'format': '',
    'editionDescription': '',
    'productDimensions': '6.00(w) x 9.10(h) x 1.10(d)'
  },
  {'isbn13': '9781982157999',
    'author': 'Alex Trebek',
    'bookTitle': 'The Answer Is...: Reflections on My Life',
    'publisherName': '	Simon & Schuster',
    'publisherLink': '/publisher',
    'publicationDate': '07/21/2020',
    'series': '',
    'bookCategory': 'Diary',
    'ageRange': '',
    'pages': 304,
    'salesRank': 20,
    'format': '',
    'editionDescription': '',
    'productDimensions': '5.50(w) x 8.50(h) x 1.10(d)'
  }
];

module.exports.arrOfBooks = arrOfBooks;